# Generated by Django 5.2.1 on 2025-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usertable_full_name_usertable_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='type',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
