# Generated by Django 5.2.1 on 2025-05-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usertable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='field_recovery_experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='languages_known',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='specialization_areas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
