# Generated by Django 5.2.1 on 2025-05-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usertable_field_recovery_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='aadhaar_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='empanelment_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/empanelment/'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='pan_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
        migrations.AddField(
            model_name='usertable',
            name='police_verification',
            field=models.FileField(blank=True, null=True, upload_to='documents/police_verification/'),
        ),
    ]
