# Generated by Django 5.2.1 on 2025-05-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usertable_aadhaar_file_usertable_empanelment_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertable',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
