# Generated by Django 5.2.1 on 2025-05-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visit_status', models.CharField(max_length=50)),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('last_visit_remarks', models.TextField(blank=True)),
                ('ptp', models.DateField(blank=True, null=True)),
                ('next_action', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('borrower_met', models.BooleanField(null=True)),
                ('visited_whom', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('amount_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interaction_remarks', models.TextField(blank=True)),
                ('ptp_date', models.DateField(blank=True, null=True)),
                ('ptp_reason', models.TextField(blank=True)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='visit_selfies/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='cases.case')),
            ],
        ),
    ]
